ubuntu-22.04:
  os: ubuntu-22.04
  nexus_token_secret: NEXUS_TEST_REPO_UPLOAD_TOKEN
  nexus_url_secret: NEXUS_TEST_REPO_URL_UBUNTU_2204

ubuntu-24.04:
  os: ubuntu-24.04
  nexus_token_secret: NEXUS_TEST_REPO_UPLOAD_TOKEN
  nexus_url_secret: NEXUS_TEST_REPO_URL_UBUNTU_2404

debian-11:
  os: debian-11
  nexus_token_secret: NEXUS_REPO_UPLOAD_TOKEN
  nexus_url_secret: NEXUS_REPO_URL_DEBIAN_11

debian-12:
  os: debian-12
  nexus_token_secret: NEXUS_REPO_UPLOAD_TOKEN
  nexus_url_secret: NEXUS_REPO_URL_DEBIAN_12

debian-13:
  os: debian-13
  nexus_token_secret: NEXUS_TEST_REPO_UPLOAD_TOKEN
  nexus_url_secret: NEXUS_TEST_REPO_URL_DEBIAN_13

rocky-8:
  os: rocky-8.10
  nexus_token_secret: NEXUS_REPO_UPLOAD_TOKEN
  nexus_url_secret: NEXUS_REPO_URL_ROCKY_8

rocky-8.7:
  os: rocky-8.7
  nexus_token_secret: NEXUS_REPO_UPLOAD_TOKEN
  nexus_url_secret: NEXUS_REPO_URL_ROCKY_8

rocky-8.10:
  os: rocky-8.10
  nexus_token_secret: NEXUS_REPO_UPLOAD_TOKEN
  nexus_url_secret: NEXUS_REPO_URL_ROCKY_8

rocky-9:
  os: rocky-9.7
  nexus_token_secret: NEXUS_TEST_REPO_UPLOAD_TOKEN
  nexus_url_secret: NEXUS_TEST_REPO_URL_ROCKY_9

rocky-9.7:
  os: rocky-9.7
  nexus_token_secret: NEXUS_TEST_REPO_UPLOAD_TOKEN
  nexus_url_secret: NEXUS_TEST_REPO_URL_ROCKY_9

rocky-10:
  os: rocky-10.1
  nexus_token_secret: NEXUS_TEST_REPO_UPLOAD_TOKEN
  nexus_url_secret: NEXUS_TEST_REPO_URL_ROCKY_10

rocky-10.1:
  os: rocky-10.1
  nexus_token_secret: NEXUS_TEST_REPO_UPLOAD_TOKEN
  nexus_url_secret: NEXUS_TEST_REPO_URL_ROCKY_10

fedora-43:
  os: fedora-43
  nexus_token_secret: NEXUS_TEST_REPO_UPLOAD_TOKEN
  nexus_url_secret: NEXUS_TEST_REPO_URL_FEDORA_43

centos-7:
  os: centos-7
  nexus_token_secret: NEXUS_TEST_REPO_UPLOAD_TOKEN
  nexus_url_secret: NEXUS_TEST_REPO_URL_CENTOS_7
