name: Confluence Upload
description: Upload files as attachments to Confluence pages

inputs:
  token:
    description: 'Confluence API token'
    required: true
  username:
    description: 'Confluence username'
    required: true
  file_path:
    description: 'Path to the file to upload'
    required: true
  space:
    description: 'Confluence space key (e.g., MAGP)'
    required: true
  page_title:
    description: 'Page title to attach file to'
    required: false
    default: 'Releases'
  comment:
    description: 'Comment for the attachment'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'
        cache: 'pip'

    - name: Install dependencies
      shell: bash
      run: pip install atlassian-python-api

    - name: Upload to Confluence
      shell: python
      env:
        CONFLUENCE_USERNAME: ${{ inputs.username }}
        CONFLUENCE_TOKEN: ${{ inputs.token }}
        FILE_PATH: ${{ inputs.file_path }}
        PAGE_TITLE: ${{ inputs.page_title }}
        SPACE: ${{ inputs.space }}
        COMMENT: ${{ inputs.comment }}
      run: |
        import os

        from atlassian.confluence import Confluence

        confluence_server = Confluence(
            url="https://confluence.ecmwf.int",
            username=os.environ["CONFLUENCE_USERNAME"],
            password=os.environ["CONFLUENCE_TOKEN"],
        )

        confluence_server.attach_file(
            file_path=os.environ["FILE_PATH"],
            name=None,
            content_type="application/binary",
            title=os.environ["PAGE_TITLE"],
            space=os.environ["SPACE"],
            comment=os.environ["COMMENT"],
        )
