name: setup-doxygen
description: Composite action to download, compile and cache doxygen
inputs:
  version:
    description: doxygen version to download
    default: 1.14.0 
    required: true

runs:
  using: composite
  steps:
    - name: Set Doxygen version
      run: echo "DOXYGEN_VERSION=${{ inputs.version }}" >> "$GITHUB_ENV"
      shell: bash
    - name: Restore cached Doxygen
      id: doxygen-cache
      uses: actions/cache@v4
      with:
        # Anything you install to this path will be reused on the next run
        path: ~/.local/doxygen
        key: doxygen-${{ runner.os }}-${{ env.DOXYGEN_VERSION }}
    - name: Build Doxygen from source
      if: steps.doxygen-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        TAG="Release_${DOXYGEN_VERSION//./_}"
        curl -L -o doxygen.tar.gz "https://github.com/doxygen/doxygen/archive/refs/tags/${TAG}.tar.gz"
        tar -xf doxygen.tar.gz
        mkdir -p doxygen-build
        cd doxygen-${TAG}/
        mkdir build && cd build
        cmake -G"Ninja" -DCMAKE_INSTALL_PREFIX="$HOME/.local/doxygen" ..
        cmake --build . --target install -j32
    - name: Add Doxygen to PATH
      run: echo "$HOME/.local/doxygen/bin" >> "$GITHUB_PATH"
      shell: bash
