name: HPC Module Deployer
description: Build and deploy HPC modules with support for CMake, Python packages, and multi-stage builds

inputs:
  # Standard CD inputs
  name:
    description: 'Build name for identification'
    required: true
  ref_name:
    description: 'Git ref name for deployment'
    required: true
  sha:
    description: 'Git commit SHA to checkout. Used instead of ref_name if provided'
    required: false
    default: ''
  dry_run:
    description: 'Dry run mode - build on HPC but skip module sync'
    required: false
    default: 'false'
  dry_run_install:
    description: 'Install module during dry runs'
    required: false
    default: 'false'
  dry_run_install_prefix:
    description: 'Custom install prefix for dry_run_install (default: $SCRATCH/dry-run-install/<module>/<ref>)'
    required: false
    default: ''

  # HPC Authentication
  github_user:
    description: 'GitHub user for authentication'
    required: true
  github_token:
    description: 'GitHub PAT for repository access'
    required: true
  troika_user:
    description: 'HPC submission user'
    required: true

  # Compiler/Platform
  platform:
    description: 'Compiler platform (gnu-14.2.0, gnu-12.2.0, gnu-8.5.0, nvidia-22.11, nvidia-24.11, intel-2021.4.0, intel-2025.0.1, amd-4.0.0)'
    required: true

  # Installation
  install_prefix:
    description: 'Custom install prefix, defaults to /usr/local/apps/<module>/<ref>'
    required: false
    default: ''
  prefix_compiler_specific:
    description: 'Suffix <compiler>/<version> to install prefix'
    required: false
    default: 'false'

  # Build Configuration
  cmake_options:
    description: 'CMake options as line-separated key=value pairs (e.g., "CMAKE_BUILD_TYPE=Release\nENABLE_TESTS=ON")'
    required: false
    default: ''
  ctest_options:
    description: 'CTest options as line separated values (e.g., "--output-on-failure\n-j=8")'
    required: false
    default: ''
  self_test:
    description: 'Run tests after building'
    required: false
    default: 'true'
  env_vars:
    description: 'Environment variables as line separated key=value pairs (e.g., "CTEST_PARALLEL_LEVEL=4")'
    required: false
    default: ''
  parallel:
    description: 'Number of parallel build jobs'
    required: false
    default: ''
  use_ninja:
    description: 'Use ninja build system instead of make'
    required: false
    default: 'true'
  force_build:
    description: 'Force rebuild, ignoring cache'
    required: false
    default: 'false'
  ecbundle:
    description: 'Use ecbundle for bundle-based projects'
    required: false
    default: 'false'
  bundle_yml:
    description: 'Path to bundle.yml for declarative bundle builds (auto-detected if present)'
    required: false
    default: ''

  # Dependencies
  dependencies:
    description: 'Build dependencies as line separated values (e.g., "owner/repo@ref\nowner/repo@ref")'
    required: false
    default: ''
  dependency_cmake_options:
    description: 'CMake options for dependencies as line separated key=value pairs (e.g., "owner/repo: -DOPTION=VALUE")'
    required: false
    default: ''
  python_dependencies:
    description: 'Python dependencies to build from source as line separated values (e.g., "owner/repo@ref\nowner/repo@ref")'
    required: false
    default: ''
  python_version:
    description: 'Python version to use for build'
    required: false
    default: ''
  python_requirements:
    description: 'Path to pip requirements file for python packages'
    required: false
    default: ''
  python_toml_opt_dep_sections:
    description: 'List of optional dependency sections specified in pyproject.toml as line separated values (e.g., "optional-dependency\noptional-dependency")'
    required: false
    default: ''
  conda_deps:
    description: 'Conda packages to install as line separated values (e.g., "package\npackage")'
    required: false
    default: ''

  # Stage Configuration (for multi-stage builds)
  stages:
    description: |
      JSON array of build stages for multi-Python or multi-config builds.
      Each stage object can have:
        - name: Stage identifier (required)
        - modules: Array of modules to load for this stage
        - cmake_options: CMake options for this stage (e.g., Boost/Python paths)
        - build_command: Custom build command (default: make -j$PARALLEL)
        - test_command: Optional test command to run before install (e.g., ctest --output-on-failure -j 8)
        - install_command: Custom install command (default: cmake --install .)
      Example: [{"name":"py312","modules":["python3/3.12","boost/1.87"],"cmake_options":"-DPython3_ROOT=...","test_command":"ctest --output-on-failure -j 8"}]
    required: false
    default: ''

  modules:
    description: 'Modules to load as line separated values (e.g., "python/3.12\nboost/1.87")'
    required: false
    default: ''
  install_command:
    description: 'Custom install command (overrides default cmake --install). Use $INSTALL_PREFIX for install path.'
    required: false
    default: ''

  # Finalization
  lock_permissions:
    description: 'Lock install directory permissions after build (chmod a-w)'
    required: false
    default: 'true'
  sync_module:
    description: 'Sync module to other clusters after build'
    required: false
    default: 'true'
  module_name:
    description: 'Module name for sync (if different from repo name)'
    required: false
    default: ''

  # Resource Options
  ntasks:
    description: 'Number of tasks for the job'
    required: false
    default: ''
  gpus:
    description: 'Number of GPUs required'
    required: false
    default: ''
  queue:
    description: 'HPC queue (nf, ng, deploy)'
    required: false
    default: ''

  # Advanced Options
  site:
    description: 'HPC site name'
    required: false
    default: 'hpc-batch'
  workdir:
    description: 'Work directory on HPC'
    required: false
    default: ''
  output_dir:
    description: 'Output directory on HPC'
    required: false
    default: ''
  post_script:
    description: 'Bash script to run after build (path relative to repo root)'
    required: false
    default: ''
  clean_before_install:
    description: 'Remove existing install directory before install (for nightly builds)'
    required: false
    default: 'false'
  install_lib_dir:
    description: 'CMake INSTALL_LIB_DIR value (lib or lib64). If set, adds -DINSTALL_LIB_DIR to cmake options.'
    required: false
    default: 'lib'
  mkdir:
    description: 'Directories to create in workdir before build as line separated values (e.g., "dir\ndir")'
    required: false
    default: ''
  pytest_cmd:
    description: 'Custom pytest command for Python package testing'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Parse configuration
      id: config
      shell: bash
      env:
        INPUT_PLATFORM: ${{ inputs.platform }}
        INPUT_STAGES: ${{ inputs.stages }}
        INPUT_DRY_RUN: ${{ inputs.dry_run }}
        INPUT_DRY_RUN_INSTALL: ${{ inputs.dry_run_install }}
        INPUT_DRY_RUN_INSTALL_PREFIX: ${{ inputs.dry_run_install_prefix }}
        INPUT_SYNC_MODULE: ${{ inputs.sync_module }}
        INPUT_SITE: ${{ inputs.site }}
        INPUT_INSTALL_PREFIX: ${{ inputs.install_prefix }}
        INPUT_MODULE_NAME: ${{ inputs.module_name }}
        INPUT_REF_NAME: ${{ inputs.ref_name }}
        INPUT_PREFIX_COMPILER_SPECIFIC: ${{ inputs.prefix_compiler_specific }}
        GITHUB_ACTION_PATH: ${{ github.action_path }}
      run: python3 "${{ github.action_path }}/scripts/parse_config.py"

    - name: Generate build template
      id: template
      shell: bash
      env:
        INPUT_STAGES: ${{ inputs.stages }}
        INPUT_CMAKE_OPTIONS: ${{ inputs.cmake_options }}
        INPUT_CTEST_OPTIONS: ${{ inputs.ctest_options }}
        INPUT_DEPENDENCIES: ${{ inputs.dependencies }}
        INPUT_DEPENDENCY_CMAKE_OPTIONS: ${{ inputs.dependency_cmake_options }}
        INPUT_PYTHON_DEPENDENCIES: ${{ inputs.python_dependencies }}
        INPUT_MODULES: ${{ inputs.modules }}
        INPUT_ENV_VARS: ${{ inputs.env_vars }}
        INPUT_INSTALL_LIB_DIR: ${{ inputs.install_lib_dir }}
        INPUT_BUNDLE_YML: ${{ inputs.bundle_yml }}
        INPUT_INSTALL_COMMAND: ${{ inputs.install_command }}
        INPUT_REF_NAME: ${{ inputs.ref_name }}
        INPUT_SHA: ${{ inputs.sha }}
        INPUT_MODULE_NAME: ${{ inputs.module_name }}
        INPUT_PARALLEL: ${{ inputs.parallel }}
        INPUT_NTASKS: ${{ inputs.ntasks }}
        INPUT_GPUS: ${{ inputs.gpus }}
        INPUT_QUEUE: ${{ inputs.queue }}
        INPUT_SITE: ${{ inputs.site }}
        INPUT_LOCK_PERMISSIONS: ${{ inputs.lock_permissions }}
        INPUT_USE_NINJA: ${{ inputs.use_ninja }}
        INPUT_SELF_TEST: ${{ inputs.self_test }}
        INPUT_FORCE_BUILD: ${{ inputs.force_build }}
        INPUT_ECBUNDLE: ${{ inputs.ecbundle }}
        INPUT_CLEAN_BEFORE_INSTALL: ${{ inputs.clean_before_install }}
        INPUT_PYTHON_VERSION: ${{ inputs.python_version }}
        INPUT_PYTHON_REQUIREMENTS: ${{ inputs.python_requirements }}
        INPUT_PYTHON_TOML_OPT_DEP_SECTIONS: ${{ inputs.python_toml_opt_dep_sections }}
        INPUT_CONDA_DEPS: ${{ inputs.conda_deps }}
        INPUT_POST_SCRIPT: ${{ inputs.post_script }}
        INPUT_MKDIR: ${{ inputs.mkdir }}
        INPUT_PYTEST_CMD: ${{ inputs.pytest_cmd }}
        INPUT_NAME: ${{ inputs.name }}
        INPUT_DRY_RUN: ${{ inputs.dry_run }}
        INPUT_DRY_RUN_INSTALL: ${{ inputs.dry_run_install }}
        INPUT_PREFIX_COMPILER_SPECIFIC: ${{ inputs.prefix_compiler_specific }}
        STEP_CONFIG_COMPILER: ${{ steps.config.outputs.compiler }}
        STEP_CONFIG_COMPILER_MODULES: ${{ steps.config.outputs.compiler_modules }}
        STEP_CONFIG_INSTALL_PREFIX: ${{ steps.config.outputs.install_prefix }}
        STEP_CONFIG_BASE_INSTALL_PREFIX: ${{ steps.config.outputs.base_install_prefix }}
        STEP_CONFIG_DO_SYNC: ${{ steps.config.outputs.do_sync }}
        GITHUB_ACTION_PATH: ${{ github.action_path }}
      run: python3 "${{ github.action_path }}/scripts/generate_template.py"

    - name: Build with ci-hpc-generic
      uses: ecmwf/reusable-workflows/ci-hpc-generic@v2
      with:
        troika_user: ${{ inputs.troika_user }}
        site: ${{ inputs.site }}
        workdir: ${{ inputs.workdir }}
        output_dir: ${{ inputs.output_dir }}
        template: ${{ steps.template.outputs.template }}
        sbatch_options: ${{ steps.template.outputs.sbatch_options }}
        template_data: |
          github_user: ${{ inputs.github_user }}
          github_token: ${{ inputs.github_token }}
          install_prefix: ${{ steps.config.outputs.install_prefix }}
