name: Python PyPI Publisher
description: Build and publish Python packages to PyPI/TestPyPI using UV

inputs:
  name:
    description: 'Build name for artifacts'
    required: true
  ref_name:
    description: 'Git ref name for release'
    required: true
  dry_run:
    description: 'Dry run mode - build only, no upload'
    required: false
    default: 'false'
  pypi_token:
    description: 'PyPI API token'
    required: false
  pypi_test_token:
    description: 'TestPyPI API token'
    required: false
  working_directory:
    description: 'Working directory for build (for monorepos)'
    required: false
    default: './'
  buildargs:
    description: 'Additional arguments for uv build command'
    required: false
    default: ''
  env_vars:
    description: 'Environment variables as line separated key=value pairs (e.g., "KEY=value")'
    required: false
    default: ''
  testpypi:
    description: 'Publish to TestPyPI instead of PyPI (overrides is_prerelease)'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Set environment variables from config
      if: inputs.env_vars != ''
      shell: bash
      run: |
        echo '${{ inputs.env_vars }}' >> $GITHUB_ENV

    - name: Build package with uv
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        echo "Building package with uv..."
        echo "Build args: ${{ inputs.buildargs }}"
        uv build ${{ inputs.buildargs }}
        echo ""
        echo "Built packages:"
        ls -lh dist/

    - name: Publish to PyPI
      if: ${{ false && inputs.dry_run != 'true' && inputs.testpypi != 'true' }} # Enable when ready
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        UV_PUBLISH_TOKEN: ${{ inputs.pypi_token }}
      run: |
        echo "Publishing to PyPI..."
        uv publish --publish-url https://upload.pypi.org/legacy/

    - name: Publish to TestPyPI
      if: ${{ inputs.dry_run != 'true' && inputs.testpypi == 'true' }}
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        UV_PUBLISH_TOKEN: ${{ inputs.pypi_test_token }}
      run: |
        echo "Publishing to TestPyPI..."
        uv publish --publish-url https://test.pypi.org/legacy/

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.run_id }}-${{ inputs.name }}
        path: ${{ inputs.working_directory }}/dist/*.whl
        if-no-files-found: error
        retention-days: 90
