name: Conda Builder
description: Build conda packages using conda/mamba

inputs:
  name:
    description: 'Build name for artifacts'
    required: true
  config:
    description: 'Build configuration JSON'
    required: true
  ref_name:
    description: 'Git ref name for artifacts'
    required: true
  dry_run:
    description: 'Dry run mode'
    required: false
    default: 'false'
  is_prerelease:
    description: 'Is this a pre-release build'
    required: false
    default: 'false'
  gh_pat:
    description: 'GitHub PAT token'
    required: false
  nexus_token:
    description: 'Nexus upload token'
    required: false
  nexus_test_token:
    description: 'Nexus test upload token'
    required: false
  skip_installation_test:
    description: 'Skip testing package installation from Nexus'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Parse build configuration
      id: config
      shell: bash -el {0}
      run: |
        python3 <<'PY'
        import json
        import os
        import sys

        raw = '''${{ inputs.config }}'''.strip()
        print(f"Raw config: {raw}")
        try:
            cfg = json.loads(raw)
        except json.JSONDecodeError as e:
            print(f"Failed to parse JSON config: {e}")
            sys.exit(1)

        conda_dir = cfg.get('conda_dir', './.cd/.conda')

        channels_list = cfg.get('channels') or ["conda-forge"]
        if not isinstance(channels_list, list):
            channels_list = [str(channels_list)]
        channels = " ".join([c for c in channels_list if c]) or "conda-forge"

        conda_build_args = cfg.get('conda_build_args', '--no-anaconda-upload') or '--no-anaconda-upload'

        # Determine Nexus URL based on prerelease flag
        is_prerelease = '${{ inputs.is_prerelease }}' == 'true'
        if is_prerelease:
            nexus_url = 'https://nexus-test.ecmwf.int/repository/conda-ecmwf-public'
            nexus_token = '${{ inputs.nexus_test_token }}'
            print("Using test Nexus repository for pre-release")
        else:
            # TODO: Use production Nexus repository for standard release
            nexus_url = 'https://nexus-test.ecmwf.int/repository/conda-ecmwf-public'
            nexus_token = '${{ inputs.nexus_test_token }}'
            print("Using production Nexus repository for standard release")

        meta_file = f"{conda_dir}/meta.yaml"
        output_folder = f"{conda_dir}/build"
        artifact_pattern = f"{output_folder}/**/*.tar.bz2"

        with open(os.environ['GITHUB_OUTPUT'], 'a', encoding='utf-8') as f:
            f.write(f"meta_file={meta_file}\n")
            f.write(f"channels={channels}\n")
            f.write(f"output_folder={output_folder}\n")
            f.write(f"artifact_pattern={artifact_pattern}\n")
            f.write(f"conda_build_args={conda_build_args}\n")
            f.write(f"nexus_url={nexus_url}\n")
            f.write(f"nexus_token={nexus_token}\n")

        print(f"Meta file: {meta_file}")
        print(f"Channels: {channels}")
        print(f"Output folder: {output_folder}")
        print(f"Artifact pattern: {artifact_pattern}")
        print(f"Conda build args: {conda_build_args}")
        print(f"Nexus URL: {nexus_url}")
        PY
        
    - name: Validate configuration files
      id: validate
      shell: bash -el {0}
      run: |
        meta_file="${{ steps.config.outputs.meta_file }}"
        
        if [[ ! -f "$meta_file" ]]; then
            echo "Meta file not found: $meta_file"
            exit 1
        fi
        
        echo "meta_dir=$(dirname $meta_file)" >> $GITHUB_OUTPUT
        echo "Configuration files validated successfully"

    - name: Setup conda env dir
      shell: bash -el {0}
      run: |
        echo "CONDA_ENVS_DIRS=$RUNNER_TEMP/envs" >> "$GITHUB_ENV"
        mkdir -p "$RUNNER_TEMP/envs"

    - name: Create conda environment
      shell: bash -el {0}
      run: |
        BUILD_ENV="build-env-${GITHUB_RUN_ID}"
        echo "BUILD_ENV=$BUILD_ENV" >> "$GITHUB_ENV"
        mamba env create -n "$BUILD_ENV"
          
    - name: Install build dependencies
      shell: bash -el {0}
      run: |
        eval "$(conda shell.bash hook)"
        conda activate "$BUILD_ENV"
        mamba install -y conda conda-build boa conda-verify conda-index
        mamba info
        mamba list
        
    - name: Build conda package
      shell: bash -el {0}
      run: |
        eval "$(conda shell.bash hook)"
        conda activate "$BUILD_ENV"
        meta_dir="${{ steps.validate.outputs.meta_dir }}"
        output_folder="${{ steps.config.outputs.output_folder }}"
        build_args="${{ steps.config.outputs.conda_build_args }}"

        echo "Building conda package from: $meta_dir"
        echo "Output folder: $output_folder"
        echo "Build args: $build_args"

        mkdir -p "$output_folder"

        conda mambabuild "$meta_dir" -c ${{ steps.config.outputs.nexus_url }} -c conda-forge --output-folder "$output_folder" $build_args
        
    - name: List built packages
      shell: bash -el {0}
      run: |
        output_folder="${{ steps.config.outputs.output_folder }}"
        echo "Built packages:"
        find "$output_folder" -name "*.tar.bz2" -o -name "*.tar.bz2" | sort
        
    - name: Verify artifacts
      shell: bash -el {0}
      run: |
        output_folder="${{ steps.config.outputs.output_folder }}"
        echo "Checking for conda packages in: $output_folder"

        # Check if conda packages exist in output folder
        if ! find "$output_folder" -name "*.tar.bz2" -type f | head -1 | grep -q .; then
            echo "No conda packages found in: $output_folder"
            echo "Available files:"
            find "$output_folder" -type f | head -20
            exit 1
        fi

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.run_id }}-${{ inputs.name }}
        path: ${{ steps.config.outputs.artifact_pattern }}
        if-no-files-found: error
        retention-days: 90

    - name: Acquire lock and upload to Nexus
      if: ${{ inputs.dry_run != 'true' }}
      shell: bash -el {0}
      run: |
        nexus_url="${{ steps.config.outputs.nexus_url }}"
        nexus_token="${{ steps.config.outputs.nexus_token }}"
        artifact_name="${{ github.run_id }}-${{ inputs.name }}"

        echo "Acquiring conda index lock and uploading to Nexus: $nexus_url"
        echo "Artifact: $artifact_name"
        echo ""

        # Run the lock acquisition script
        python3 "${{ github.action_path }}/scripts/acquire_lock.py" \
            --nexus-url "$nexus_url" \
            --nexus-token "$nexus_token" \
            --artifact-name "$artifact_name" \
            --caller-run-id "${{ github.run_id }}" \
            --caller-repo "${{ github.repository }}" \
            --gh-pat "${{ inputs.gh_pat }}"

        echo ""
        echo "All packages and indexes uploaded to Nexus successfully!"

    - name: Test package installation from Nexus
      if: ${{ inputs.dry_run != 'true' && inputs.skip_installation_test != 'true' }}
      shell: bash -el {0}
      run: |
        output_folder="${{ steps.config.outputs.output_folder }}"
        nexus_url="${{ steps.config.outputs.nexus_url }}"

        echo "Testing package installation from Nexus..."

        # Get package name and version from built packages
        packages=$(find "$output_folder" -name "*.tar.bz2" -type f)

        for package in $packages; do
            package_name=$(basename "$package")
            echo ""
            echo "Testing installation of: $package_name"

            # Extract package name and version
            pkg_base=$(echo "$package_name" | sed -E 's/-[0-9]+(\.[0-9]+)*-.*//')
            pkg_version=$(echo "$package_name" | sed -E 's/^[^-]+-([0-9]+(\.[0-9]+)*).*/\1/')

            echo "Package: $pkg_base"
            echo "Version: $pkg_version"

            # Create a test environment
            test_env="test-install-${GITHUB_RUN_ID}-${RANDOM}"
            echo "Creating test environment: $test_env"

            eval "$(conda shell.bash hook)"

            # Create environment and install the EXACT version from Nexus
            if mamba create -n "$test_env" -c "$nexus_url" -c conda-forge "${pkg_base}=${pkg_version}" -y; then
                echo "Successfully installed ${pkg_base}=${pkg_version} from Nexus"

                # Verify the exact version is installed
                conda activate "$test_env"
                installed_version=$(conda list "$pkg_base" | grep "$pkg_base" | awk '{print $2}')

                if [ "$installed_version" = "$pkg_version" ]; then
                    echo "Verified exact version: $installed_version matches $pkg_version"
                else
                    echo "Version mismatch: installed $installed_version but expected $pkg_version"
                    conda deactivate
                    conda env remove -n "$test_env" -y
                    exit 1
                fi
                conda deactivate

                # Clean up test environment
                conda env remove -n "$test_env" -y
                echo "Test environment removed"
            else
                echo "Failed to install ${pkg_base}=${pkg_version} from Nexus"
                echo "This could mean the package was not uploaded successfully"
                exit 1
            fi
        done

        echo ""
        echo "All packages successfully installed from Nexus with correct versions!"
