name: Update PR-Description
description: Updates a PR-Description with a custom payload inside a marker so that the payload can be updated.
inputs:
  text:
    description: text to be added
    required: true
  marker:
    description: unique marker to identify this type of update
    required: true
  repo:
    description: owner/repo 
    required: true
  pr:
    description: PR number
    required: true
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - shell: bash
      run: python -m pip install requests
    - shell: bash
      run: python $GITHUB_ACTION_PATH/update-pr-description.py --marker ${{ inputs.marker }} --payload "${{ inputs.text }}" --repo ${{ inputs.repo }} --pr ${{ inputs.pr }}
