name: Tarball Builder
description: Build source tarballs using ecbuild on platform-builder runners

inputs:
  name:
    description: 'Build name for artifacts'
    required: true
  ref_name:
    description: 'Git ref name for artifacts'
    required: true
  dry_run:
    description: 'Dry run mode - build only, no deployment'
    required: false
    default: 'false'
  ecbuild_version:
    description: 'ecbuild version/tag to checkout (defaults to latest release)'
    required: false
    default: ''
  cmake_options:
    description: 'Additional CMake options for ecbuild'
    required: false
    default: ''

outputs:
  tarball_path:
    description: 'Path to generated tarball file'
    value: ${{ steps.find-tarball.outputs.tarball_path }}

runs:
  using: composite
  steps:
    - name: Install ecbuild
      shell: bash
      run: |
        ecbuild_version="${{ inputs.ecbuild_version }}"

        if [ -z "$ecbuild_version" ]; then
          echo "Fetching latest ecbuild release from GitHub API..."
          ecbuild_version=$(curl -sL https://api.github.com/repos/ecmwf/ecbuild/releases/latest \
            | grep '"tag_name":' \
            | sed -E 's/.*"tag_name": *"([^"]+)".*/\1/')

          if [ -z "$ecbuild_version" ]; then
            echo "::error::Failed to fetch latest ecbuild release from GitHub API"
            exit 1
          fi
          echo "Using latest release: $ecbuild_version"
        fi

        echo "Cloning ecbuild to ${{ runner.temp }}/ecbuild..."
        git clone --depth 1 --branch "$ecbuild_version" \
          https://github.com/ecmwf/ecbuild.git "${{ runner.temp }}/ecbuild"
        echo "${{ runner.temp }}/ecbuild/bin" >> $GITHUB_PATH
        echo "Added ecbuild to PATH"

    - name: Create build directory
      shell: bash
      run: |
        echo "Creating build directory..."
        mkdir -p build

    - name: Run ecbuild
      shell: bash
      run: |
        cmake_options="${{ inputs.cmake_options }}"

        echo "Running ecbuild in build directory..."
        cd build

        if [ -n "$cmake_options" ]; then
            echo "CMake options: $cmake_options"
            ecbuild $cmake_options ..
        else
            ecbuild ..
        fi

    - name: Build source package
      shell: bash
      run: |
        echo "Building source package..."
        cd build
        make package_source

        echo ""
        echo "Build complete!"

    - name: List generated tarballs
      shell: bash
      run: |
        echo "Generated tarballs:"
        find build -name "*.tar.gz" -type f | sort

    - name: Verify artifacts
      shell: bash
      run: |
        echo "Checking for tarball in: build"

        if ! find build -name "*.tar.gz" -type f | head -1 | grep -q .; then
            echo "No tarball found in: build"
            echo "Available files:"
            find build -type f | head -20
            exit 1
        fi

        echo "Tarball verification successful!"

    - name: Find tarball path
      id: find-tarball
      shell: bash
      run: |
        tarball=$(find build -name "*.tar.gz" -type f | head -1)

        echo "tarball_path=$tarball" >> $GITHUB_OUTPUT
        echo "Found tarball: $tarball"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.run_id }}-${{ inputs.name }}
        path: build/*.tar.gz
        if-no-files-found: error
        retention-days: 90
