sync_clusters:
  aa-batch: [ab, ac, ad]
  ab-batch: [aa, ac, ad]
  ac-batch: [aa, ab, ad]
  ad-batch: [aa, ab, ac]
  ag-batch: []
  lumi: []

tag_clusters:
  aa-batch: [aa, ab, ac, ad]
  ab-batch: [aa, ab, ac, ad]
  ac-batch: [aa, ab, ac, ad]
  ad-batch: [aa, ab, ac, ad]
  ag-batch: [ag]
  lumi: []
