name: Release Action
description: Create GitHub releases with artifact uploads

inputs:
  config:
    description: 'Full configuration object'
    required: true
  ref_name:
    description: 'Git ref name for release'
    required: true
  artifacts_dir:
    description: 'Directory containing downloaded artifacts'
    required: false
    default: 'release-artifacts'

runs:
  using: composite
  steps:
    - name: Parse release configuration
      id: config
      shell: bash
      run: |
        config='${{ inputs.config }}'
        
        # Parse release configuration
        release_name=$(echo "$config" | yq eval '.release.config.name // "Release ${{ inputs.ref_name }}"' -)
        release_body=$(echo "$config" | yq eval '.release.config.body // "## Changes\nSee the changelog for details."' -)
        prerelease=$(echo "$config" | yq eval '.release.config.prerelease // false' -)
        draft=$(echo "$config" | yq eval '.release.config.draft // false' -)
        make_latest=$(echo "$config" | yq eval '.release.config.make_latest // "true"' -)
        
        echo "release_name=$release_name" >> $GITHUB_OUTPUT
        echo "prerelease=$prerelease" >> $GITHUB_OUTPUT
        echo "draft=$draft" >> $GITHUB_OUTPUT
        echo "make_latest=$make_latest" >> $GITHUB_OUTPUT
        
        # Handle multiline body
        echo "release_body<<EOF" >> $GITHUB_OUTPUT
        echo "$release_body" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: ${{ github.run_id }}-*
        merge-multiple: true
        path: ${{ inputs.artifacts_dir }}
        
    - name: List downloaded artifacts
      shell: bash
      run: |
        echo "Downloaded artifacts:"
        find ${{ inputs.artifacts_dir }} -type f | sort
        
    - name: Create release file list
      id: files
      shell: bash
      run: |
        echo "Creating file list for release..."
        # Find all files in the artifacts directory
        files_list=$(find ${{ inputs.artifacts_dir }} -type f | sort)
        
        if [[ -z "$files_list" ]]; then
            echo "No files found for release in ${{ inputs.artifacts_dir }}"
            exit 1
        fi
        
        echo "Files to be released:"
        echo "$files_list"
        
        echo "files_list<<EOF" >> $GITHUB_OUTPUT
        echo "$files_list" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        
    - name: Create GitHub release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ inputs.ref_name }}
        name: ${{ steps.config.outputs.release_name }}
        body: ${{ steps.config.outputs.release_body }}
        files: ${{ steps.files.outputs.files_list }}
        prerelease: ${{ steps.config.outputs.prerelease }}
        draft: ${{ steps.config.outputs.draft }}
        make_latest: ${{ steps.config.outputs.make_latest }}
        token: ${{ github.token }}
        
    - name: Release summary
      shell: bash
      run: |
        echo "## Release Created" >> $GITHUB_STEP_SUMMARY
        echo "- **Tag**: ${{ inputs.ref_name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Name**: ${{ steps.config.outputs.release_name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Prerelease**: ${{ steps.config.outputs.prerelease }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Draft**: ${{ steps.config.outputs.draft }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Uploaded Files" >> $GITHUB_STEP_SUMMARY
        find ${{ inputs.artifacts_dir }} -type f | sort | while read -r file; do
            echo "- $(basename "$file")" >> $GITHUB_STEP_SUMMARY
        done