name: Nightly Pytest
description: Github action to run nightly pytests
inputs:
  python-version:
    description: The version of Python binary to use.
    required: false
    default: '3.x'
    type: string
  repository:
    description: The source repository name, in case it differs from the current one. Repository names should
      follow the standard Github `owner/name` format.
    required: true
    type: string
  ref:
    description: The source repository reference, in case it differs from the current one.
    required: true
    type: string
  install-package:
    description: Install package before running tests.
    required: false
    default: "-e .[all, tests]" 
    type: string
  test-directory:
    description: The working directory to run the tests from.
    required: false
    default: "."
    type: string
  pytest-options:
    description: Additional options to pass to pytest.
    required: false
    default: ""
    type: string
  manual:
    description: Trigger the action manually and bypass the latest commit check.
    required: false
    default: "false"
    type: string
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}

    - name: Print latest commit
      run: echo ${{ github.sha }}

    - id: should_run
      name: Check latest commit is less than a day
      if: ${{ inputs.manual == 'false' }}
      run: |
        echo "should_run=false" >> $GITHUB_ENV
        if git rev-list --after="24 hours" ${{ github.sha }} | grep .; then
          echo "should_run=true" >> $GITHUB_ENV
        else
          echo "should_run=false" >> $GITHUB_ENV
        fi

    - name: Set up Python
      if: ${{ env.should_run == 'true' || inputs.manual == 'true' }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'

    - name: Install dependencies
      if: ${{ env.should_run == 'true' || inputs.manual == 'true' }}
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-md pytest-emoji
        python -m pip install ${{ inputs.install-package }}

    - name: Run integration tests
      if: ${{ env.should_run == 'true' || inputs.manual == 'true' }}
      run: python -m pytest ${{ inputs.test-directory }} ${{ inputs.pytest-options }}