name: Python Conda Builder
description: Build Python packages using conda/mamba

inputs:
  name:
    description: 'Build name for artifacts'
    required: true
  config:
    description: 'Build configuration JSON'
    required: true
  ref_name:
    description: 'Git ref name for artifacts'
    required: true
  python_version:
    description: 'Python version override'
    required: false
  dry_run:
    description: 'Dry run mode'
    required: false
    default: 'false'
  is_prerelease:
    description: 'Is this a pre-release build'
    required: false
    default: 'false'
  gh_pat:
    description: 'GitHub PAT token'
    required: false
  nexus_token:
    description: 'Nexus upload token'
    required: false
  skip_installation_test:
    description: 'Skip testing package installation from Nexus'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Parse build configuration
      id: config
      shell: bash
      run: |
        python3 <<'PY'
        import json
        import os
        import sys

        raw = '''${{ inputs.config }}'''.strip()
        print(f"Raw config: {raw}")
        try:
            cfg = json.loads(raw)
        except json.JSONDecodeError as e:
            print(f"Failed to parse JSON config: {e}")
            sys.exit(1)

        run_id = os.environ.get('GITHUB_RUN_ID', '')

        remote_repo = cfg.get('remote_repo', '') or ''
        remote_ref = cfg.get('remote_ref', 'main') or 'main'
        remote_path = cfg.get('remote_path', '.conda') or '.conda'

        conda_dir = f".conda-{run_id}" if remote_repo else ".conda"

        channels_list = cfg.get('channels') or ["conda-forge"]
        if not isinstance(channels_list, list):
            channels_list = [str(channels_list)]
        channels = " ".join([c for c in channels_list if c]) or "conda-forge"

        conda_build_args = cfg.get('conda_build_args', '--no-anaconda-upload') or '--no-anaconda-upload'

        # Determine Nexus URL based on prerelease flag
        is_prerelease = '${{ inputs.is_prerelease }}' == 'true'
        if is_prerelease:
            nexus_url = 'https://nexus-test.ecmwf.int/repository/conda-ecmwf-public'
            print("Using test Nexus repository for pre-release")
        else:
            # TODO: Use production Nexus repository for standard release
            nexus_url = 'https://nexus-test.ecmwf.int/repository/conda-ecmwf-public'
            print("Using production Nexus repository for standard release")

        meta_file = f"{conda_dir}/meta.yaml"
        output_folder = f"{conda_dir}/build"
        artifact_pattern = f"{output_folder}/**/*.tar.bz2"

        outputs = {
            'conda_dir': conda_dir,
            'meta_file': meta_file,
            'channels': channels,
            'output_folder': output_folder,
            'artifact_pattern': artifact_pattern,
            'conda_build_args': conda_build_args,
            'remote_repo': remote_repo,
            'remote_ref': remote_ref,
            'remote_path': remote_path,
            'nexus_url': nexus_url,
        }

        with open(os.environ['GITHUB_OUTPUT'], 'a', encoding='utf-8') as fh:
            for k, v in outputs.items():
                fh.write(f"{k}={v}\n")
                print(f"Set output {k}={v}")
        PY
        
    - name: Fetch remote conda configuration
      if: ${{ steps.config.outputs.remote_repo != '' }}
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.gh_pat || github.token }}
      run: |
        remote_repo="${{ steps.config.outputs.remote_repo }}"
        remote_ref="${{ steps.config.outputs.remote_ref }}"
        remote_path="${{ steps.config.outputs.remote_path }}"
        
        echo "Fetching conda configuration from remote repository:"
        echo "  Repository: $remote_repo"
        echo "  Reference: $remote_ref"
        echo "  Path: $remote_path"
        
        # Create temporary directory for remote checkout
        temp_dir=$(mktemp -d)
        echo "Created temporary directory: $temp_dir"
        
        # Clone the remote repository using standard git commands
        # Format the repository URL with token authentication
        if [[ "$remote_repo" == *"/"* ]] && [[ "$remote_repo" != http* ]]; then
            # Assume GitHub format: owner/repo
            repo_url="https://x-access-token:${GH_TOKEN}@github.com/${remote_repo}.git"
        else
            # Full URL provided - insert token if it's an HTTPS GitHub URL
            if [[ "$remote_repo" == https://github.com/* ]]; then
                repo_url="${remote_repo/https:\/\/github.com\//https://x-access-token:${GH_TOKEN}@github.com/}"
                if [[ "$repo_url" != *.git ]]; then
                    repo_url="${repo_url}.git"
                fi
            else
                repo_url="$remote_repo"
            fi
        fi
        
        echo "Cloning repository: $repo_url"
        git clone --depth 1 --branch "$remote_ref" "$repo_url" "$temp_dir"
        
        # Create local conda directory if it doesn't exist
        mkdir -p ${{ steps.config.outputs.conda_dir }}
        
        # Copy conda configuration files from remote repository
        if [[ -d "$temp_dir/$remote_path" ]]; then
            echo "Copying files from $temp_dir/$remote_path to ${{ steps.config.outputs.conda_dir }}"
            cp -r "$temp_dir/$remote_path"/* ${{ steps.config.outputs.conda_dir }}
        else
            echo "Remote path $remote_path not found in repository"
            exit 1
        fi
        
        # Clean up temporary directory
        rm -rf "$temp_dir"
        echo "Remote conda configuration fetched successfully"
        
    - name: Validate configuration files
      id: validate
      shell: bash
      run: |
        meta_file="${{ steps.config.outputs.meta_file }}"
        
        if [[ ! -f "$meta_file" ]]; then
            echo "Meta file not found: $meta_file"
            exit 1
        fi
        
        echo "meta_dir=$(dirname $meta_file)" >> $GITHUB_OUTPUT
        echo "Configuration files validated successfully"

    - name: Setup conda env dir
      shell: bash
      run: |
        echo "CONDA_ENVS_DIRS=$RUNNER_TEMP/envs" >> "$GITHUB_ENV"
        mkdir -p "$RUNNER_TEMP/envs"

    - name: Create conda environment
      shell: bash -el {0}
      run: |
        BUILD_ENV="build-env-${GITHUB_RUN_ID}"
        echo "BUILD_ENV=$BUILD_ENV" >> "$GITHUB_ENV"
        mamba env create -n "$BUILD_ENV"
          
    - name: Install build dependencies
      shell: bash -el {0}
      run: |
        eval "$(conda shell.bash hook)"
        conda activate "$BUILD_ENV"
        mamba install -y conda conda-build boa conda-verify conda-index
        mamba info
        mamba list
        
    - name: Build conda package
      shell: bash -el {0}
      run: |
        eval "$(conda shell.bash hook)"
        conda activate "$BUILD_ENV"
        meta_dir="${{ steps.validate.outputs.meta_dir }}"
        output_folder="${{ steps.config.outputs.output_folder }}"
        build_args="${{ steps.config.outputs.conda_build_args }}"

        echo "Building conda package from: $meta_dir"
        echo "Output folder: $output_folder"
        echo "Build args: $build_args"

        mkdir -p "$output_folder"

        conda mambabuild "$meta_dir" -c ${{ steps.config.outputs.nexus_url }} -c conda-forge --output-folder "$output_folder" $build_args
        
    - name: List built packages
      shell: bash -el {0}
      run: |
        output_folder="${{ steps.config.outputs.output_folder }}"
        echo "Built packages:"
        find "$output_folder" -name "*.tar.bz2" -o -name "*.tar.bz2" | sort
        
    - name: Verify artifacts
      shell: bash -el {0}
      run: |
        output_folder="${{ steps.config.outputs.output_folder }}"
        echo "Checking for conda packages in: $output_folder"

        # Check if conda packages exist in output folder
        if ! find "$output_folder" -name "*.tar.bz2" -type f | head -1 | grep -q .; then
            echo "No conda packages found in: $output_folder"
            echo "Available files:"
            find "$output_folder" -type f | head -20
            exit 1
        fi

    - name: Upload to Nexus
      if: ${{ inputs.dry_run != 'true' }}
      shell: bash -el {0}
      run: |
        output_folder="${{ steps.config.outputs.output_folder }}"
        nexus_url="${{ steps.config.outputs.nexus_url }}"

        echo "Uploading conda packages to Nexus: $nexus_url"

        # Activate build environment and install dependencies
        eval "$(conda shell.bash hook)"
        conda activate "$BUILD_ENV"

        echo "Installing conda-index and requests..."
        mamba install -y conda-index requests

        # Run the rebuild script
        echo "Rebuilding conda index..."
        python "${{ github.action_path }}/scripts/rebuild_conda_index.py" \
            --package-dir "$output_folder" \
            --nexus-url "$nexus_url" \
            --nexus-token "${{ inputs.nexus_token }}"

        echo ""
        echo "All packages and indexes uploaded to Nexus successfully!"

    - name: Test package installation from Nexus
      if: ${{ inputs.dry_run != 'true' && inputs.skip_installation_test != 'true' }}
      shell: bash -el {0}
      run: |
        output_folder="${{ steps.config.outputs.output_folder }}"
        nexus_url="${{ steps.config.outputs.nexus_url }}"

        echo "Testing package installation from Nexus..."

        # Get package name and version from built packages
        packages=$(find "$output_folder" -name "*.tar.bz2" -type f)

        for package in $packages; do
            package_name=$(basename "$package")
            echo ""
            echo "Testing installation of: $package_name"

            # Extract package name without version/build info
            pkg_base=$(echo "$package_name" | sed 's/-.*//')

            # Create a test environment
            test_env="test-install-${GITHUB_RUN_ID}-${RANDOM}"
            echo "Creating test environment: $test_env"

            eval "$(conda shell.bash hook)"

            # Create environment and install package from Nexus
            if mamba create -n "$test_env" -c "$nexus_url" -c conda-forge "$pkg_base" -y; then
                echo "✓ Successfully installed $pkg_base from Nexus"

                # Verify package is installed
                conda activate "$test_env"
                if conda list | grep -q "$pkg_base"; then
                    echo "✓ Package $pkg_base verified in environment"
                else
                    echo "✗ Package $pkg_base not found in environment"
                    conda deactivate
                    conda env remove -n "$test_env" -y
                    exit 1
                fi
                conda deactivate

                # Clean up test environment
                conda env remove -n "$test_env" -y
                echo "Test environment removed"
            else
                echo "✗ Failed to install $pkg_base from Nexus"
                exit 1
            fi
        done

        echo ""
        echo "All packages successfully installed from Nexus!"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.run_id }}-${{ inputs.name }}
        path: ${{ steps.config.outputs.artifact_pattern }}
        if-no-files-found: error
        retention-days: 90
