name: Python Conda Builder
description: Build Python packages using conda/mamba

inputs:
  name:
    description: 'Build name for artifacts'
    required: true
  config:
    description: 'Build configuration JSON'
    required: true
  ref_name:
    description: 'Git ref name for artifacts'
    required: true
  python_version:
    description: 'Python version override'
    required: false
  dry_run:
    description: 'Dry run mode'
    required: false
    default: 'false'
  gh_pat:
    description: 'GitHub PAT token'
    required: false

runs:
  using: composite
  steps:
    - name: Parse build configuration
      id: config
      shell: bash
      run: |
        python3 <<'PY'
        import json
        import os
        import sys

        raw = '''${{ inputs.config }}'''.strip()
        print(f"Raw config: {raw}")
        try:
            cfg = json.loads(raw)
        except json.JSONDecodeError as e:
            print(f"Failed to parse JSON config: {e}")
            sys.exit(1)

        run_id = os.environ.get('GITHUB_RUN_ID', '')

        remote_repo = cfg.get('remote_repo', '') or ''
        remote_ref = cfg.get('remote_ref', 'main') or 'main'
        remote_path = cfg.get('remote_path', '.conda') or '.conda'

        conda_dir = f".conda-{run_id}" if remote_repo else ".conda"

        channels_list = cfg.get('channels') or ["conda-forge"]
        if not isinstance(channels_list, list):
            channels_list = [str(channels_list)]
        channels = " ".join([c for c in channels_list if c]) or "conda-forge"

        conda_build_args = cfg.get('conda_build_args', '--no-anaconda-upload') or '--no-anaconda-upload'

        environment_file = f"{conda_dir}/environment.yaml"
        meta_file = f"{conda_dir}/meta.yaml"
        output_folder = f"{conda_dir}/build"
        artifact_pattern = f"{output_folder}/**/*.tar.bz2"

        outputs = {
            'conda_dir': conda_dir,
            'environment_file': environment_file,
            'meta_file': meta_file,
            'channels': channels,
            'output_folder': output_folder,
            'artifact_pattern': artifact_pattern,
            'conda_build_args': conda_build_args,
            'remote_repo': remote_repo,
            'remote_ref': remote_ref,
            'remote_path': remote_path,
        }

        with open(os.environ['GITHUB_OUTPUT'], 'a', encoding='utf-8') as fh:
            for k, v in outputs.items():
                fh.write(f"{k}={v}\n")
                print(f"Set output {k}={v}")
        PY
        
    - name: Fetch remote conda configuration
      if: ${{ steps.config.outputs.remote_repo != '' }}
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.gh_pat || github.token }}
      run: |
        remote_repo="${{ steps.config.outputs.remote_repo }}"
        remote_ref="${{ steps.config.outputs.remote_ref }}"
        remote_path="${{ steps.config.outputs.remote_path }}"
        
        echo "Fetching conda configuration from remote repository:"
        echo "  Repository: $remote_repo"
        echo "  Reference: $remote_ref"
        echo "  Path: $remote_path"
        
        # Create temporary directory for remote checkout
        temp_dir=$(mktemp -d)
        echo "Created temporary directory: $temp_dir"
        
        # Clone the remote repository using standard git commands
        # Format the repository URL with token authentication
        if [[ "$remote_repo" == *"/"* ]] && [[ "$remote_repo" != http* ]]; then
            # Assume GitHub format: owner/repo
            repo_url="https://x-access-token:${GH_TOKEN}@github.com/${remote_repo}.git"
        else
            # Full URL provided - insert token if it's an HTTPS GitHub URL
            if [[ "$remote_repo" == https://github.com/* ]]; then
                repo_url="${remote_repo/https:\/\/github.com\//https://x-access-token:${GH_TOKEN}@github.com/}"
                if [[ "$repo_url" != *.git ]]; then
                    repo_url="${repo_url}.git"
                fi
            else
                repo_url="$remote_repo"
            fi
        fi
        
        echo "Cloning repository: $repo_url"
        git clone --depth 1 --branch "$remote_ref" "$repo_url" "$temp_dir"
        
        # Create local conda directory if it doesn't exist
        mkdir -p ${{ steps.config.outputs.conda_dir }}
        
        # Copy conda configuration files from remote repository
        if [[ -d "$temp_dir/$remote_path" ]]; then
            echo "Copying files from $temp_dir/$remote_path to ${{ steps.config.outputs.conda_dir }}"
            cp -r "$temp_dir/$remote_path"/* ${{ steps.config.outputs.conda_dir }}
        else
            echo "Remote path $remote_path not found in repository"
            exit 1
        fi
        
        # Clean up temporary directory
        rm -rf "$temp_dir"
        echo "Remote conda configuration fetched successfully"
        
    - name: Validate configuration files
      id: validate
      shell: bash
      run: |
        environment_file="${{ steps.config.outputs.environment_file }}"
        meta_file="${{ steps.config.outputs.meta_file }}"
        
        # Validation
        if [[ ! -f "$environment_file" ]]; then
            echo "Environment file not found: $environment_file"
            exit 1
        fi
        
        if [[ ! -f "$meta_file" ]]; then
            echo "Meta file not found: $meta_file"
            exit 1
        fi
        
        echo "meta_dir=$(dirname $meta_file)" >> $GITHUB_OUTPUT
        echo "Configuration files validated successfully"

    - name: Create conda environment
      shell: bash -el {0}
      run: |
        BUILD_ENV="build-env-${GITHUB_RUN_ID}"
        echo "BUILD_ENV=$BUILD_ENV" >> "$GITHUB_ENV"
        mamba env create -n "$BUILD_ENV" -f "${{ steps.config.outputs.environment_file }}"
          
    - name: Install build dependencies
      shell: bash -el {0}
      run: |
        eval "$(conda shell.bash hook)"
        conda activate "$BUILD_ENV"
        mamba install -y conda conda-build boa
        mamba info
        mamba list
        
    - name: Validate meta.yaml
      shell: bash -el {0}
      run: |
        eval "$(conda shell.bash hook)"
        conda activate "$BUILD_ENV"
        meta_file="${{ steps.config.outputs.meta_file }}"
        echo "Validating meta.yaml: $meta_file"
        conda render "$meta_file" --output
        
    - name: Build conda package
      shell: bash -el {0}
      run: |
        eval "$(conda shell.bash hook)"
        conda activate "$BUILD_ENV"
        meta_dir="${{ steps.validate.outputs.meta_dir }}"
        output_folder="${{ steps.config.outputs.output_folder }}"
        build_args="${{ steps.config.outputs.conda_build_args }}"

        echo "Building conda package from: $meta_dir"
        echo "Output folder: $output_folder"
        echo "Build args: $build_args"

        mkdir -p "$output_folder"

        conda mambabuild "$meta_dir" --output-folder "$output_folder" $build_args
        
    - name: List built packages
      shell: bash -el {0}
      run: |
        output_folder="${{ steps.config.outputs.output_folder }}"
        echo "Built packages:"
        find "$output_folder" -name "*.tar.bz2" -o -name "*.tar.bz2" | sort
        
    - name: Verify artifacts
      shell: bash -el {0}
      run: |
        output_folder="${{ steps.config.outputs.output_folder }}"
        echo "Checking for conda packages in: $output_folder"
        
        # Check if conda packages exist in output folder
        if ! find "$output_folder" -name "*.tar.bz2" -type f | head -1 | grep -q .; then
            echo "No conda packages found in: $output_folder"
            echo "Available files:"
            find "$output_folder" -type f | head -20
            exit 1
        fi
        
    - name: Upload artifacts
      if: ${{ inputs.dry_run != 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.ref_name }}-${{ inputs.name }}
        path: ${{ steps.config.outputs.artifact_pattern }}
        if-no-files-found: error
        retention-days: 90
        
    - name: Summary
      shell: bash -el {0}
      run: |
        echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Build Name**: ${{ inputs.name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Environment File**: ${{ steps.config.outputs.environment_file }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Meta File**: ${{ steps.config.outputs.meta_file }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Channels**: ${{ steps.config.outputs.channels }}" >> $GITHUB_STEP_SUMMARY
        if [[ "${{ inputs.dry_run }}" == "true" ]]; then
            echo "- **Mode**: Dry Run (no artifacts uploaded)" >> $GITHUB_STEP_SUMMARY
        fi